on: [push,workflow_dispatch]
name: Deploy Web App

env:
  AZURE_WEBAPP_NAME: githubdemogenerator  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'          # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'                 # set this to the dot net version to use

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: azure/login@v2
      with:
        auth-type: SERVICE_PRINCIPAL
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    # Checkout the repo
    - uses: actions/checkout@v4
      
    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 
        
      # Run dotnet build and publish
    - name: dotnet build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/webapp' 
          
      # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v3
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/webapp'
        
    - uses: azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        app-settings-json: '${{ secrets.APP_SETTINGS }}' 
      id: settings
    - run: echo "The webapp-url is ${{ steps.settings.outputs.webapp-url }}"
    - run: |
        az logout
